footprint: [[0.1, 0.0], [0.0, 0.1], [0.0, -0.1], [-0.1, 0.0]]
robot_radius: 0.10
track_unknown_space: true

transform_tolerance: 2.0
update_frequency: 2.0
publish_frequency: 1.0

resolution: 0.05

global_frame: map
robot_base_frame: base_link
rolling_window: false

plugins: 

    - {name: static,                  type: "costmap_2d::StaticLayer"}
    - {name: explore_boundary,        type: "robot_explore::BoundedExploreLayer"}
    - {name: explore_sensor,          type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,               type: "costmap_2d::InflationLayer"}

static:
    map_topic: move_base/global_costmap/costmap   
    subscribe_to_updates: true

explore_boundary:
    resize_to_boundary: false

explore_sensor:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: /scan}

inflation:
    inflation_radius: 0.15
